import string

ALLOWED_SYMBOLS = string.ascii_letters + string.digits
CUSTOM_URL_LENGHT = 16
GENERATED_SHORT_LENGTH = 6
ORIGINAL_URL_LENGTH = 256
MAX_ATTEMPTS = 3

SHORT_ROUTE = 'open_link'
REGEX = f'^[{ALLOWED_SYMBOLS}]+$'
